### ISSUE TITLE
How to postMessage continuously?

### ISSUE THREAD

**Issue by zc1789284658** [israelss/vue-worker#16]
hello,I'm a user of ur vue-worker,It's useful,but I encounter a problem

The scene:
    I need a timerTask to post new Date to mainPage,So I write a demo as follow:
    I write a timeout/interval in  Fuction.run , but it's not take effect,could u give me a resolution? 

 preThx for help~

    methods: {
    startClock() {
        this.clock_worker = this.$worker
        .run(() =>{
           //var timer=()=>{
            //     setTimeout(timer,1000);
            // }
            // timer();     
            // setInterval(postMessage(new Date()),1000)
            //---------PS:  SETTIMEOUT && SETINTERVAL is not take effect
        })
        .then(res => console.log(res)) // logs 'this.$worker run 1: Function in other thread'
        .catch(console.error); // logs any possible error
    }
    },
    mounted() {
    if (typeof Worker === "undefined") {
      this.$message("您的浏览器不支持WebWorker,某些特性可能无法完美呈现");
    } else {
      this.startClock();
    }
    }
     };

**Comment by GitHubJiKe** [comment]
vue-worker is  is a wrapper for [simple-web-worker](https://github.com/israelss/simple-web-worker).
So, through read [simple-web-worker](https://github.com/israelss/simple-web-worker)'s source code and documents, you will know, `run` and `create` api just create  a disposable web worker, when your work executed, worker would run close, that's why your interval or timeout doesn't work. you can check the [source code](https://github.com/israelss/simple-web-worker/blob/master/src/utils.js), line number: 62.
To resolve this problem, I committed one [PR](https://github.com/israelss/simple-web-worker/pull/16). By this way, you can use async action func.

**Comment by zc1789284658** [comment]
thank you. it's useful !
